spring.application.name=Ecom
server.port=8081

spring.datasource.url=jdbc:h2:file:./data/ecomdb
spring.datasource.driver-class-name=org.h2.Driver

#set this to update so that everytime you restart the app, the db entities remain saved and updates only if required
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true

spring.datasource.username=aryan
spring.datasource.password=raut

spring.